### ISSUE TITLE
Unexpected radar.fixed_angle['data'].shape

### ISSUE THREAD

**Issue by juhi24** [MeteoSwiss/pyart#27]
Consider data [202308071610_radar.polar.fikor.h5.gz](https://github.com/MeteoSwiss/pyart/files/12290388/202308071610_radar.polar.fikor.h5.gz) and code

```python
import pyart
radar = pyart.aux_io.read_odim_h5('/path/to/202308071610_radar.polar.fikor.h5',
                                  include_datasets=['dataset1', 'dataset2'])
pyart.graph.common.generate_title(radar, 'reflectivity', 0)
```
This fails with 
```
File ~/.virtualenvs/vaimennuskorjain/lib64/python3.11/site-packages/pyart/graph/common.py:260 in generate_title
    l1 = f"{generate_radar_name(radar)} {fixed_angle:.1f} Deg. {time_str} "

TypeError: unsupported format string passed to numpy.ndarray.__format__
```

Reason:

```python
In [37]: radar.fixed_angle['data'].shape
Out[37]: (2, 1)
```
is the wrong shape. `generate_title` expects it to be flat.

Symptom: Cannot autogenerate titles to figures made from this ODIM H5 file. A simple `.flatten()` somewhere could do the trick.

**Comment by wolfidan** [comment]
Hi @juhi24 ,
Thanks a lot for opening this issue and for providing the data!

I will look into it later this afternoon,

**Comment by wolfidan** [comment]
Hi @juhi24 , I made a new PR that fixes this issue. I also saw some other issues with the odim reader/writer in Py-ART
- Order of 'data' within 'datasets' was not conserved, so the fields in the radar object were in a different order than the original odim file. This made the written file different from the original file.
- Some parameters needed to be flattened to match the original ones in the hdf5
- the way some parameters were defined by Py-ART (rstart for example) were not consistent with the original value in the ODIM
- the writer was relying on the parameter _ray_angle_res_ which was not defined by the reader.

I took the opportunity to write a set of unit tests for ODIM h5 reader and writers, and used a part of the file you provided as reference. I hope this is ok for you, otherwise please let me know.

**Comment by wolfidan** [comment]
For the ARM version, I think at some point I should make a PR with our fixed reader and with the writer as well (I don't think they have a writer). But I will like it would require some more tests, I am not too sure about our implementation,

**Comment by juhi24** [comment]
Excellent, thank you! The data is released as open data by the FMI under the CC BY 4.0 license. So, feel free to use it.

I'm very happy that you fixed also the `ray_angle_res` issue, as I was about to report that one next.

I bet both the ARM version maintainers and users would be pleased if you submitted the reader patch soon. The writer could be submitted later if you don't feel it's mature enough quite yet.
